# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-07-22 02:43
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Post', '0007_auto_20170722_0936'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='item_occupation',
            field=models.IntegerField(default=1),
        ),
    ]
