# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-07-22 02:24
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Degree',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('degree_id', models.IntegerField()),
                ('degree_name', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Office',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('office_id', models.IntegerField()),
                ('office_name', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Users',
            fields=[
                ('user_id', models.AutoField(primary_key=True, serialize=False)),
                ('user_name', models.CharField(max_length=200)),
                ('user_username', models.CharField(max_length=200)),
                ('user_password', models.CharField(max_length=200)),
                ('user_degreefk', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='polls.Degree')),
                ('user_officefk', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='polls.Office')),
            ],
        ),
    ]
