# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-07-22 03:19
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Post', '0010_auto_20170722_1119'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='item_occupation',
            field=models.IntegerField(default=0),
        ),
    ]
