# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-08-12 03:42
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Profile', '__first__'),
    ]

    operations = [
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('course_name', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Item',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('item_name', models.CharField(max_length=200)),
                ('item_quantity', models.IntegerField(default=1)),
                ('item_condition', models.IntegerField(default=0)),
                ('item_occupation', models.IntegerField(default=0)),
                ('item_img', models.FileField(upload_to='')),
                ('item_status', models.IntegerField(default=0)),
                ('item_coursefk', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='Post.Course')),
                ('item_userfk', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Profile.User')),
            ],
        ),
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tag_word', models.CharField(max_length=200)),
                ('tag_itemfk', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Post.Item')),
            ],
        ),
    ]
