# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-07-27 18:21
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Post', '0015_auto_20170728_0221'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='item_occupation',
            field=models.IntegerField(default=0),
        ),
    ]
