# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-08-12 03:49
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Profile', '__first__'),
        ('Post', '0018_item_item_status'),
    ]

    operations = [
        migrations.CreateModel(
            name='Offer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('offer_type', models.IntegerField(default=0)),
                ('offer_cash', models.IntegerField(blank=True, default=0, null=True)),
                ('offer_status', models.IntegerField(default=0)),
                ('offer_clientfk', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Profile.User')),
                ('offer_itemexfk', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='Post.Item')),
                ('offer_itemfk', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, related_name='offer_itemfk', to='Post.Item')),
            ],
        ),
    ]
