# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-08-15 12:02
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Post', '0019_offer'),
    ]

    operations = [
        migrations.AddField(
            model_name='offer',
            name='offer_comment',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
