# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-07-22 01:03
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Post', '0002_tag'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='item_img',
            field=models.FileField(upload_to=''),
        ),
    ]
